# Generated by Django 4.2 on 2023-05-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenApp', '0002_rename_pic_service_pic1_service_pic2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
