# Generated by Django 4.2 on 2023-05-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenApp', '0003_alter_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description2',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
