# Generated by Django 4.2 on 2023-05-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenApp', '0005_alter_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='pic3',
            field=models.ImageField(blank=True, default=True, null=True, upload_to='service'),
        ),
        migrations.AddField(
            model_name='service',
            name='pic4',
            field=models.ImageField(blank=True, default=True, null=True, upload_to='service'),
        ),
        migrations.AddField(
            model_name='service',
            name='pic5',
            field=models.ImageField(blank=True, default=True, null=True, upload_to='service'),
        ),
    ]
