# Generated by Django 4.2 on 2023-05-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenApp', '0006_service_pic3_service_pic4_service_pic5'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pic', models.ImageField(upload_to='team')),
                ('name', models.CharField(max_length=80)),
                ('profession', models.CharField(max_length=100)),
            ],
        ),
    ]
