# Generated by Django 4.2 on 2023-05-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenApp', '0007_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('profession', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
