# Generated by Django 4.2 on 2023-05-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenApp', '0008_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='experience'),
        ),
    ]
