# Generated by Django 4.2 on 2023-05-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenApp', '0010_alter_service_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='quote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('service', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
